# 基础镜像
FROM redis
# author
MAINTAINER thh

# 挂载目录
VOLUME /home/thh/redis
# 创建目录
RUN mkdir -p /thh/thh/redis
# 指定路径
WORKDIR /home/thh/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/thh/redis/redis.conf
