# 基础镜像
FROM nginx
# author
MAINTAINER thh

# 挂载目录
VOLUME /home/thh/projects/web-ui
VOLUME /home/thh/projects/file_data
# 创建目录
RUN mkdir -p /home/thh/projects/web-ui/{vue-admin,vue-web}  /home/thh/projects/file_data
# 指定路径
WORKDIR /home/thh/projects/web-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/admin/dist /home/thh/projects/web-ui/vue-admin
COPY ./html/web/dist /home/thh/projects/web-ui/vue-web
COPY ./html/file/data /home/thh/projects/file_data
